#Docker-compose file for Nginx php mysql projects
#specific for laravel development
version: '3.8'

services:

  #Main containers ready for deployment
  #Nginx server
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    depends_on:
      - php
      - mysql
    volumes:
#      - code:/var/www/html # production
      - ./src:/var/www/html # development
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  #PHP 8 Interpreter
  php:
    image: app
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
#      - code:/var/www/html # production
      - ./src:/var/www/html:delegated # development

  #Mysql Database V8
  mysql:
    image: mysql:8.0
    env_file:
      - ./environment/mysql.env
    volumes:
    - database:/var/lib/mysql

#  Utility containers just for development
  phpmyadmin:
    image: 'phpmyadmin'
    ports:
      - 8080:80
    links:
      - mysql:db

  artisan:
    image: app
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - php

  composer:
    image: composer:latest
    working_dir: /var/www/html
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    volumes:
      - ./src:/var/www/html

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html

volumes:
#  code: # production
  database:
