#Docker-compose file for php mysql projects
#specific for laravel development
#the images are ready to deploy
version: '3.8'

services:

  #Main containers ready for deployment
  #Nginx server
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    depends_on:
      - php
      - mysql
    volumes:
      - code:/var/www/html # production
#      - ./src:/var/www/html # development
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  #PHP 8 Interpreter
  php:
    image: laravel:8.0
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - code:/var/www/html # production
#      - ./src:/var/www/html:delegated # development

  #Mysql Database V8
  mysql:
    image: library/mysql:8.0
    env_file:
      - ./environment/mysql.env
    volumes:
    - database:/var/lib/mysql

#  Utility containers just for development

  phpmyadmin:
    image: 'phpmyadmin'
    ports:
      - 8080:80
    links:
      - mysql:db

  composer:
    image: composer:latest
    working_dir: /var/www/html
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    volumes:
      - code:/var/www/html # production
#      - ./src:/var/www/html # development

  artisan:
    image: artisan:dev
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - code:/var/www/html # production
#      - ./src:/var/www/html # development
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - code:/var/www/html # production
#      - ./src:/var/www/html # development

volumes:
  code:
  database: