#Docker-compose file for php mysql projects
#specific for laravel development
#the images are ready to deploy
version: '3.8'

services:
  #Main containers ready for deployment
  server: #Nginx server
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php: #PHP 8 Interpreter
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql: #Mysql Database V8
    image: library/mysql:8.0
    env_file:
      - ./environment/mysql.env
  phpmyadmin: #Phpmyadmin for Mysql
    image: 'phpmyadmin'
    ports:
      - 8080:80
    links:
      - mysql:db

  #Utilty containers just for development
  composer:
    image: composer:latest
    working_dir: /var/www/html
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
